"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Maximum time it may take to produce the prompt
command_timeout = 3000

# Note: Not supported in Powershell
# @see: https://starship.rs/advanced-config/#enable-right-prompt
right_format = """
[](bg:transparent fg:#1e2939)\
$time\
$memory_usage\
[](fg:#1e2939 bg:transparent)\
"""

# Left prompt. This is displayed on the left side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
format = """
[](bg:#transparent fg:#ff637e)\
$os\
$username\
[](fg:#ff637e bg:#1e2939)\
$directory\
${custom.pregit}\
$git_branch\
$git_state\
$git_metrics\
$git_status\
${custom.postgit}\
${custom.nogit}\
$package\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$nim\
$rust\
$scala\
$docker_context\
$character\
$line_break\
[  ](bold fg:#ff637e)\
"""

########################
#   Special sections   #
########################

# Exit code indicator
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bg:#364153 fg:#ff637e)[󱇫](bg:#ff637e fg:#030712)[](fg:#ff637e bg:transparent)'
error_symbol = '[](bg:#364153 fg:#ffba00)[󱇫](bg:#ffba00 fg:#4d0218)[](fg:#ffba00 bg:transparent)'
format = '$symbol '

# cross-platform way to check if we are in a git repo, takes 200ms
[custom.nogit]
when = ''' git rev-parse --git-dir ; test $? = False '''
format = '[ ](bg:#1e2939)'
disabled = true

# Either `Administrator`, `root` or the current user's username.
[username]
show_always = true
style_user = "bg:#ff637e fg:#030712"
style_root = "bg:#ff637e fg:#030712"
format = '[ $user]($style)'
disabled = false


# Displays a symbol that represents the current operating system
[os]
style = "bg:#ff637e fg:#030712"
format = '[$symbol]($style)'
disabled = false                # This doesn't work in pwsh in Webstorm terminal.

# The current directory
[directory]
style = "bg:#1e2939 fg:#f3f4f6"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[hostname]
ssh_symbol = ""

[memory_usage]
symbol = "󰍛"

[time]
disabled = false
time_format = "%R"         # Hour:Minute Format
style = "bg:#1e2939"
format = '[$time]($style)'

#######################
#   Version control   #
#######################


[git_branch]
symbol = ""
style = "bg:#364153 fg:#99a1af"
format = '[](fg:#1e2939 bg:#364153)[ $symbol](bg:#364153 fg:#ff637e)[ $branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING ](bg:#364153 fg:bold red)'
rebase = '[ REBASING ](bg:#364153 fg:bold green)'
merge = '[ MERGING ](bg:#364153 fg:bold yellow)'
bisect = '[🔍 BISECTING ](bg:#364153 fg:bold blue)'
am = '[AM](bg:#364153 fg:bold green)'
am_or_rebase = '[AM/REBASE ](bg:#364153 fg:bold green)'
revert = '[󰕍 REVERTING ](bg:#364153 fg:bold red)'

[git_metrics]
added_style = "bg:#364153 fg:#ffba00"
deleted_style = "bg:#364153 fg:#ff637e"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[git_status]
style = "bg:#364153 fg:#ff637e"
conflicted = '='                                                                          # This branch has merge conflicts.
ahead = ''
behind = ''
diverged = '󱡷'
up_to_date = ''
untracked = '?'
stashed = ''
modified = ''
staged = ''
renamed = '»'
deleted = '✘'
format = '([($all_status )($ahead_behind )]($style))[🔍 BISECTING](bg:#364153 fg:#1e2939)'

[fossil_branch]
symbol = ""

[hg_branch]
symbol = ""

[pijul_channel]
symbol = ""

############################
#   Contexts (canonical)   #
############################

[nodejs]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[bun]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ (context) ]($style)'

[package]
format = '($style)[> $symbol$version ]($style)'
symbol = '📦 '
version_format = 'v${raw}'
style = 'bold 208 bg:#1e2939'
display_private = false
disabled = true
################
#   Contexts   #
################

[aws]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[c]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[conda]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[dart]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[gradle]
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[haxe]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[java]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[ocaml]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[perl]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[php]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[python]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[rlang]
symbol = "󰟔"
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[swift]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

[zig]
symbol = ""
style = "bg:#1e2939 fg:#f3f4f6"
format = '[$symbol](bg:#1e2939 fg:#ff637e)[ ($version) ]($style)'

#############
#   Other   #
#############

[nix_shell]
symbol = ""

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

